# Generated by Django 4.1.5 on 2023-01-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('web', models.CharField(max_length=100)),
                ('hp', models.CharField(blank=True, max_length=254, null=True)),
                ('alamat', models.TextField(default='Jawa Barat')),
                ('jenis_sekolah', models.CharField(choices=[('SMA', 'Sekolah Menengah Atas'), ('SMK', 'Sekolah Menengah Kejuruan'), ('UNIV', 'Perguruan Tinggi')], max_length=4)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
