# Generated by Django 4.1.5 on 2023-01-18 04:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sekolah', '0002_remove_sekolah_jenis_sekolah_remove_sekolah_web_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sekolah',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Sekolah'},
        ),
        migrations.AddField(
            model_name='sekolah',
            name='create_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sekolah_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sekolah',
            name='npsn',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterModelTable(
            name='sekolah',
            table='sekolah',
        ),
    ]
