# Generated by Django 4.1.5 on 2023-01-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasiswa',
            name='alamat',
            field=models.TextField(default='Jawa Barat'),
        ),
    ]
