# Generated by Django 4.1.5 on 2023-01-16 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekolah', '0001_initial'),
        ('siswa', '0002_alter_datasiswa_alamat'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasiswa',
            name='sekolah',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sekolah.sekolah'),
        ),
    ]
